CREATE TABLE IF NOT EXISTS public.memories (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               user_id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    context_json JSONB,
    importance_score INTEGER NOT NULL,
    archived BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
    );

CREATE TABLE IF NOT EXISTS public.memory_outcomes (
                                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                      memory_id BIGINT,
                                                      outcome_summary TEXT,
                                                      satisfaction_score INTEGER NOT NULL,
                                                      recorded_at TIMESTAMPTZ,
                                                      CONSTRAINT fk_memory_outcome
                                                      FOREIGN KEY (memory_id)
    REFERENCES public.memories(id)
    ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS public.memory_relationships (
                                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                           from_memory_id BIGINT,
                                                           to_memory_id BIGINT,
                                                           type VARCHAR(255) CHECK (
                                                                                       type IN ('CAUSED_BY','FOLLOWED_BY','SUPPORTS','CONTRADICTS','REVISITS')
    ),
    weight INTEGER NOT NULL,
    created_at TIMESTAMPTZ
    );

CREATE INDEX IF NOT EXISTS idx_memory_user ON public.memories(user_id);
CREATE INDEX IF NOT EXISTS idx_memory_created ON public.memories(created_at);
CREATE INDEX IF NOT EXISTS idx_from_memory ON public.memory_relationships(from_memory_id);
CREATE INDEX IF NOT EXISTS idx_to_memory ON public.memory_relationships(to_memory_id);
